# Site setings
name: 'Julien'
description: 'Web Application Architect'
meta_description: 'Personal website and blog about PHP, web development and IT stuffs.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'julienzendcon.jpg'
  greetings: "Hi there! My name is Julien Guittard. I'm a web application architect, author and speaker based in Paris, France. Happy reading!"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://julienguittard.com/
disqus: 'julienguittard'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: hello@julienguittard.com

# Social links
twitter: 'julienguittard'
github: 'jguittard'
medium: '@username'
instagram: 'julienguittard'
linkedin: 'julienguittard'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /blog/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
